// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/home-layout/CommandCenter.tsx": () => import("../components/mockups/home-layout/CommandCenter.tsx"),
  "./components/mockups/home-layout/HomeAmplified.tsx": () => import("../components/mockups/home-layout/HomeAmplified.tsx"),
  "./components/mockups/home-layout/HomeWarmer.tsx": () => import("../components/mockups/home-layout/HomeWarmer.tsx"),
  "./components/mockups/home-layout/SplitDashboard.tsx": () => import("../components/mockups/home-layout/SplitDashboard.tsx"),
  "./components/mockups/home-layout/WelcomeCard.tsx": () => import("../components/mockups/home-layout/WelcomeCard.tsx"),
  "./components/mockups/home-layout/WelcomeCardEditorial.tsx": () => import("../components/mockups/home-layout/WelcomeCardEditorial.tsx"),
  "./components/mockups/home-layout/WelcomeCardTight.tsx": () => import("../components/mockups/home-layout/WelcomeCardTight.tsx")
};
